# Generated by Django 3.2.4 on 2021-06-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habilidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('framework', models.ManyToManyField(to='habilidades.FrameWork')),
                ('linguagem', models.ManyToManyField(to='habilidades.Linguagem')),
            ],
            options={
                'verbose_name': 'Desenvolvedor',
                'verbose_name_plural': 'Desenvolvedores',
            },
        ),
    ]
