# Generated by Django 3.2.4 on 2021-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0002_auto_20210619_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='linguagem',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
